const swaggerJsdoc = require('swagger-jsdoc')

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Wallet connections API FS25on_team7',
      version: '1.0.0',
      description: 'Backend server Express API autogenerated swagger doc',
    },
    servers: [
      {
        url: 'https://fs25on-team7-wallet-backend.herokuapp.com/',
      },
    ],
  },
  apis: ['./routes/api/**/*.js'],
}

const swaggerSpec = swaggerJsdoc(options)

module.exports = { swaggerSpec }

// module.export = (app) => {
//   app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs))
// }
